# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4a4a5faea15c4023cb761e825b58dff64efd6cfd1db9699527c425ef73e5677e650cc9cb1d1ec49b3d2a227b0d59fd1f9ff0f12d25427353a38ea7946b620c1

test:
  secret_key_base: 828301ef0d1f09cf41a0f75c4eb519b76f9311b5cab7301b7db33918076f28f8f6dec8eb03519186a06909f10657ffbd8adffc8900eca7acf45599bcca529b0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
